//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class BaseReward :  Bright.Config.BeanBase 
{
    public BaseReward(JSONNode _json) 
    {
        { if(!_json["level"].IsNumber) { throw new SerializationException(); }  Level = _json["level"]; }
        { if(!_json["exp"].IsNumber) { throw new SerializationException(); }  Exp = _json["exp"]; }
        { if(!_json["sexp"].IsNumber) { throw new SerializationException(); }  Sexp = _json["sexp"]; }
        { if(!_json["money"].IsNumber) { throw new SerializationException(); }  Money = _json["money"]; }
        { if(!_json["gold"].IsNumber) { throw new SerializationException(); }  Gold = _json["gold"]; }
        { if(!_json["gold_coupon"].IsNumber) { throw new SerializationException(); }  GoldCoupon = _json["gold_coupon"]; }
        { var __json0 = _json["reputes"]; if(!__json0.IsArray) { throw new SerializationException(); } Reputes = new System.Collections.Generic.List<Repute>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Repute __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Repute.DeserializeRepute(__e0);  }  Reputes.Add(__v0); }   }
        PostInit();
    }

    public BaseReward(int level, int exp, int sexp, int money, int gold, int gold_coupon, System.Collections.Generic.List<Repute> reputes ) 
    {
        this.Level = level;
        this.Exp = exp;
        this.Sexp = sexp;
        this.Money = money;
        this.Gold = gold;
        this.GoldCoupon = gold_coupon;
        this.Reputes = reputes;
        PostInit();
    }

    public static BaseReward DeserializeBaseReward(JSONNode _json)
    {
        return new BaseReward(_json);
    }

    public int Level { get; private set; }
    public int Exp { get; private set; }
    public int Sexp { get; private set; }
    public int Money { get; private set; }
    public int Gold { get; private set; }
    public int GoldCoupon { get; private set; }
    public System.Collections.Generic.List<Repute> Reputes { get; private set; }

    public const int __ID__ = 1133378944;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Reputes) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Reputes) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Level:" + Level + ","
        + "Exp:" + Exp + ","
        + "Sexp:" + Sexp + ","
        + "Money:" + Money + ","
        + "Gold:" + Gold + ","
        + "GoldCoupon:" + GoldCoupon + ","
        + "Reputes:" + Bright.Common.StringUtil.CollectionToString(Reputes) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
