//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class BaseRewardCfg : ConfigBase
{
    private readonly Dictionary<string, baserw> _dataMap;
    private readonly List<baserw> _dataList;
    
	public BaseRewardCfg()
    {
         _dataMap = new Dictionary<string, baserw>();
        _dataList = new List<baserw>();
    }
	
    public BaseRewardCfg(JSONNode _json)
    {
        _dataMap = new Dictionary<string, baserw>();
        _dataList = new List<baserw>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = baserw.Deserializebaserw(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.RewardKey, _v);
        }
        PostInit();
    }
	
	public void load(JSONNode _json)
    {        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = baserw.Deserializebaserw(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.RewardKey, _v);
        }
        PostInit();
    }

    public Dictionary<string, baserw> DataMap => _dataMap;
    public List<baserw> DataList => _dataList;

    public baserw GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public baserw Get(string key) => _dataMap[key];
    public baserw this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}