//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class ItemGroup :  Bright.Config.BeanBase 
{
    public ItemGroup(JSONNode _json) 
    {
        { if(!_json["groupid"].IsNumber) { throw new SerializationException(); }  Groupid = _json["groupid"]; }
        { var __json0 = _json["grpitems"]; if(!__json0.IsArray) { throw new SerializationException(); } Grpitems = new System.Collections.Generic.List<ItemList>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemList __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemList.DeserializeItemList(__e0);  }  Grpitems.Add(__v0); }   }
        PostInit();
    }

    public ItemGroup(int groupid, System.Collections.Generic.List<ItemList> grpitems ) 
    {
        this.Groupid = groupid;
        this.Grpitems = grpitems;
        PostInit();
    }

    public static ItemGroup DeserializeItemGroup(JSONNode _json)
    {
        return new ItemGroup(_json);
    }

    public int Groupid { get; private set; }
    public System.Collections.Generic.List<ItemList> Grpitems { get; private set; }

    public const int __ID__ = -159408372;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Grpitems) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Grpitems) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Groupid:" + Groupid + ","
        + "Grpitems:" + Bright.Common.StringUtil.CollectionToString(Grpitems) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
