//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class ItemRewardCfg : ConfigBase
{
    private readonly Dictionary<string, itemrw> _dataMap;
    private readonly List<itemrw> _dataList;
    
	public ItemRewardCfg()
    {
         _dataMap = new Dictionary<string, itemrw>();
        _dataList = new List<itemrw>();
    }
	
    public ItemRewardCfg(JSONNode _json)
    {
        _dataMap = new Dictionary<string, itemrw>();
        _dataList = new List<itemrw>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = itemrw.Deserializeitemrw(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.RewardKey, _v);
        }
        PostInit();
    }
	
	public void load(JSONNode _json)
    {        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = itemrw.Deserializeitemrw(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.RewardKey, _v);
        }
        PostInit();
    }

    public Dictionary<string, itemrw> DataMap => _dataMap;
    public List<itemrw> DataList => _dataList;

    public itemrw GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public itemrw Get(string key) => _dataMap[key];
    public itemrw this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}