//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class ItemList :  Bright.Config.BeanBase 
{
    public ItemList(JSONNode _json) 
    {
        { if(!_json["rate"].IsNumber) { throw new SerializationException(); }  Rate = _json["rate"]; }
        { var __json0 = _json["items"]; if(!__json0.IsArray) { throw new SerializationException(); } Items = new System.Collections.Generic.List<ItemOne>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemOne __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemOne.DeserializeItemOne(__e0);  }  Items.Add(__v0); }   }
        PostInit();
    }

    public ItemList(int rate, System.Collections.Generic.List<ItemOne> items ) 
    {
        this.Rate = rate;
        this.Items = items;
        PostInit();
    }

    public static ItemList DeserializeItemList(JSONNode _json)
    {
        return new ItemList(_json);
    }

    public int Rate { get; private set; }
    public System.Collections.Generic.List<ItemOne> Items { get; private set; }

    public const int __ID__ = 1241924209;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Items) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Items) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Rate:" + Rate + ","
        + "Items:" + Bright.Common.StringUtil.CollectionToString(Items) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
