//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class ItemOne :  Bright.Config.BeanBase 
{
    public ItemOne(JSONNode _json) 
    {
        { if(!_json["sid"].IsNumber) { throw new SerializationException(); }  Sid = _json["sid"]; }
        { if(!_json["amount"].IsNumber) { throw new SerializationException(); }  Amount = _json["amount"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        PostInit();
    }

    public ItemOne(int sid, int amount, string name ) 
    {
        this.Sid = sid;
        this.Amount = amount;
        this.Name = name;
        PostInit();
    }

    public static ItemOne DeserializeItemOne(JSONNode _json)
    {
        return new ItemOne(_json);
    }

    public int Sid { get; private set; }
    public int Amount { get; private set; }
    public string Name { get; private set; }

    public const int __ID__ = -514124237;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Sid:" + Sid + ","
        + "Amount:" + Amount + ","
        + "Name:" + Name + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
