//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class Repute :  Bright.Config.BeanBase 
{
    public Repute(JSONNode _json) 
    {
        { if(!_json["repute_type"].IsString) { throw new SerializationException(); }  ReputeType = _json["repute_type"]; }
        { if(!_json["repute_val"].IsString) { throw new SerializationException(); }  ReputeVal = _json["repute_val"]; }
        PostInit();
    }

    public Repute(string repute_type, string repute_val ) 
    {
        this.ReputeType = repute_type;
        this.ReputeVal = repute_val;
        PostInit();
    }

    public static Repute DeserializeRepute(JSONNode _json)
    {
        return new Repute(_json);
    }

    public string ReputeType { get; private set; }
    public string ReputeVal { get; private set; }

    public const int __ID__ = -1850648567;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ReputeType:" + ReputeType + ","
        + "ReputeVal:" + ReputeVal + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
