//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public BaseRewardCfg BaseRewardCfg {get; }
    public ItemRewardCfg ItemRewardCfg {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        BaseRewardCfg = new BaseRewardCfg(loader("baserewardcfg")); 
        tables.Add("BaseRewardCfg", BaseRewardCfg);
        ItemRewardCfg = new ItemRewardCfg(loader("itemrewardcfg")); 
        tables.Add("ItemRewardCfg", ItemRewardCfg);
        PostInit();

        BaseRewardCfg.Resolve(tables); 
        ItemRewardCfg.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        BaseRewardCfg.TranslateText(translator); 
        ItemRewardCfg.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}