// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Bag.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Proto.Bag
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfBagInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"itemList")]
        public global::System.Collections.Generic.List<NtfItemInfo> itemLists { get; } = new global::System.Collections.Generic.List<NtfItemInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfItemInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sid")]
        public int Sid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pos")]
        public int Pos { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"amount")]
        public int Amount { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"key")]
        public int Key { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"quality")]
        public int Quality { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfItemUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pos")]
        public int Pos { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"amount")]
        public int Amount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfItemDel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqUseItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int itemID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int useNum { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"param1")]
        public int Param1 { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"param2")]
        public int Param2 { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"param3")]
        public int Param3 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RspUseItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorID { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
