// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Login.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Proto.Login
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqRegisterAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string idNo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string idName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"info")]
        public clientInfo Info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RspRegisterAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int regionID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public long playerID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string userName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public int loginType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"info")]
        public clientInfo Info { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string curVer { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public int engineVer { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int isSetup { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RspLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int lastRegionID { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"list")]
        public global::System.Collections.Generic.List<PlayerInfo> Lists { get; } = new global::System.Collections.Generic.List<PlayerInfo>();

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string idNo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"todayplaytime")]
        public int Todayplaytime { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"monthcharge")]
        public int Monthcharge { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"srvtime")]
        public long Srvtime { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int totalPlayTime { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public int verifyState { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int isAdult { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public int isHoliday { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqCreateRole : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int regionID { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"info")]
        public clientInfo Info { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"sex")]
        public int Sex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RspCreateRole : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqEnterGame : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int regionID { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"info")]
        public clientInfo Info { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"sex")]
        public int Sex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RspEnterGame : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class clientInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"package_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PackageName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"app_udid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AppUdid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"device")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Device { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"device_udid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceUdid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"model_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ModelName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"platform")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Platform { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"os")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Os { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"sdk")]
        public int Sdk { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"channel")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Channel { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Language { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfQuickUpdateList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"codeList")]
        public global::System.Collections.Generic.List<string> codeLists { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqVerifyIDCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string idNo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string idName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"device")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Device { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RspVerifyIDCard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int verifyState { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int isAdult { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"srvtime")]
        public long Srvtime { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int isHoliday { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int verifyCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfKickOutFd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        public int Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfVerifyInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int verifyState { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int verifyCode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int isAdult { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int isHoliday { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
