// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Npc.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Proto.Npc
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqNpcLook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"npcid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Npcid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RspNpcLook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorID { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"talkopt")]
    public partial class Talkopt : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tid")]
        public int Tid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"opt")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Opt { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"opttype")]
        public int Opttype { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"optargs", IsPacked = true)]
        public int[] Optargs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfNpcTalk : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"npcid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Npcid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"icon")]
        public int Icon { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"opts")]
        public global::System.Collections.Generic.List<Talkopt> Opts { get; } = new global::System.Collections.Generic.List<Talkopt>();

        [global::ProtoBuf.ProtoMember(6, Name = @"talkgroupid")]
        public int Talkgroupid { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"talkid")]
        public int Talkid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqNpcRespond : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"npcid", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Npcid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"idx")]
        public int Idx { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RspNpcRespond : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int errorID { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
