// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Scene.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Proto.Scene
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleDesc : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"color")]
        public int Color { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"weapon")]
        public int Weapon { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"weapon_color")]
        public int WeaponColor { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"weapon_eff")]
        public int WeaponEff { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"weapon_eff_color")]
        public int WeaponEffColor { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"hair")]
        public int Hair { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"hair_color")]
        public int HairColor { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"cap")]
        public int Cap { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"cap_color")]
        public int CapColor { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"wing")]
        public int Wing { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"wing_color")]
        public int WingColor { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"ride")]
        public int Ride { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"ride_color")]
        public int RideColor { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"aura")]
        public int Aura { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"fairy")]
        public int Fairy { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"track")]
        public int Track { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqMapMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"startx")]
        public int Startx { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"starty")]
        public int Starty { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"steps", IsPacked = true)]
        public int[] Steps { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfMapTrack : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y")]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"dx")]
        public int Dx { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"dy")]
        public int Dy { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfMapAddPlayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y")]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"shape")]
        public int Shape { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"desc")]
        public RoleDesc Desc { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfMapAddSummon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
        public long Pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sid")]
        public int Sid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"shape")]
        public int Shape { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"quality")]
        public int Quality { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"desc")]
        public RoleDesc Desc { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfMapDelSummon : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
        public long Pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sid")]
        public int Sid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfMapAddNpc : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y")]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sid")]
        public int Sid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"shape")]
        public int Shape { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"dir")]
        public int Dir { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"desc")]
        public RoleDesc Desc { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfMapAddGoods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y")]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sid")]
        public int Sid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"shape")]
        public int Shape { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"owners", IsPacked = true)]
        public long[] Owners { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfHeroGoto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public int Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfHeroEnterScene : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
        public long Pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scid")]
        public long Scid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"scsid")]
        public int Scsid { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"resid")]
        public int Resid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"scname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Scname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"y")]
        public int Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfMapTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"leaderid")]
        public long Leaderid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"flag")]
        public int Flag { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"logo")]
        public int Logo { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"members", IsPacked = true)]
        public long[] Members { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
