// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Team.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Proto.Team
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqInviteTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pid")]
        public long Pid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"inviter")]
        public long Inviter { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqJoinTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long leaderID { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"jointype")]
        public int Jointype { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqAwayTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rejoin")]
        public bool Rejoin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqLeaveTeam : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqKickMember : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long playerID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqRecallMember : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long playerID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReqChangeLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long playerID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemberInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long playerID { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"shape")]
        public int Shape { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"classes")]
        public int Classes { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"grade")]
        public int Grade { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"desc", IsPacked = true)]
        public int[] Descs { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"status")]
        public int Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfTeamInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"logo")]
        public int Logo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"lineup")]
        public int Lineup { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"members")]
        public global::System.Collections.Generic.List<MemberInfo> Members { get; } = new global::System.Collections.Generic.List<MemberInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NtfTeamInvite : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"leaderid")]
        public int Leaderid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"inviter")]
        public int Inviter { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"invitername")]
        public int Invitername { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"pid")]
        public int Pid { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"name")]
        public int Name { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"shape")]
        public int Shape { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"classes")]
        public int Classes { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"grade")]
        public int Grade { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
