// Dynamically generated by config tool. Do not modify the text content manually.

namespace Model.DB
{
    //BaseBlock
    public class BaseBlock : ModelData
    {
        /// <summary>
        /// 关卡主id
        /// <summary>
        public int main_id;
        /// <summary>
        /// 地图名
        /// <summary>
        public string map;
        /// <summary>
        /// 射击次数
        /// <summary>
        public int shoot_times;
        /// <summary>
        /// 奖励的金钱数
        /// <summary>
        public int money;
        /// <summary>
        /// 是否室外场景(0:否， 1：是)
        /// <summary>
        public int isOutScene;
        /// <summary>
        /// 是否是最后一关( 1：是，其他为否，只以第一个配置为1的为准)
        /// <summary>
        public int isLastBlock;

    }
    //BaseSkin
    public class BaseSkin : ModelData
    {
        /// <summary>
        /// 图片路径
        /// <summary>
        public string path;
        /// <summary>
        /// 价格
        /// <summary>
        public int cost;

    }
    //BaseWeapon
    public class BaseWeapon : ModelData
    {
        /// <summary>
        /// 图片路径
        /// <summary>
        public string path;
        /// <summary>
        /// 价格
        /// <summary>
        public int cost;

    }
}