// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Type.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Proto.Common
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Desc : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"color")]
        public int Color { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"weapon")]
        public int Weapon { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"weapon_color")]
        public int WeaponColor { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"weapon_eff")]
        public int WeaponEff { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"weapon_eff_color")]
        public int WeaponEffColor { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"hair")]
        public int Hair { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"hair_color")]
        public int HairColor { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"cap")]
        public int Cap { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"cap_color")]
        public int CapColor { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"wing")]
        public int Wing { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"wing_color")]
        public int WingColor { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"ride")]
        public int Ride { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"ride_color")]
        public int RideColor { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"aura")]
        public int Aura { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"fairy")]
        public int Fairy { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"track")]
        public int Track { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
